server:
  port: 8080
spring:
  datasource:
      druid:
        initial-size: 2
        min-idle: 1
        max-active: 20
        max-wait: 60000
        time-between-eviction-runsMillis: 60000
        min-evictable-idle-timeMillis: 300000
        validation-query: select * FROM travel_fly.user_info
        test-while-idle: true
        #testOnBorrow能够确保我们每次都能获取到可用的连接，但如果设置成true，则每次获取连接的时候都要到数据库验证连接有效性，这在高并发的时候会造成性能下降
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-open-prepared-statements: 20
        max-pool-prepared-statement-per-connection-size: 20
        filters: stat
        connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=50000
        use-global-data-source-stat: true
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: zhao535226554504
      username: admin
      url: jdbc:mysql://database-1.cfpfie2tks4e.us-east-1.rds.amazonaws.com:3306/zhtdb
      type: com.alibaba.druid.pool.DruidDataSource
#  devtools:
#    restart:
#      enabled: false#mybatis
mybatis:
  # type-aliases-package批量设置别名作用：就是在mapper.xml文件中直接写类名，不配置就需要写类的全路径名
  type-aliases-package: com.example.GrandWorldG.entity
  mapper-locations:  classpath:/mapper/*Mapper.xml
#  mapper、model采用mybatis-generator-core自动解析数据库生成
#  gradle构建时src/main/java目录下的非.java结尾的文件不会被编译，所以需要将myabtis对应的xml文件移至resources目录，并在application.yaml文件配置路径