server:
  port: 8081
spring:
  datasource:
      druid:
        initial-size: 8
        min-idle: 1
        max-active: 20
        max-wait: 60000
        time-between-eviction-runsMillis: 60000
        min-evictable-idle-timeMillis: 300000
        validation-query: select * FROM travel_fly.user_info
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-open-prepared-statements: 20
        max-pool-prepared-statement-per-connection-size: 20
        filters: stat
        connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        use-global-data-source-stat: true
      driver-class-name: org.postgresql.Driver
      password: postgres
      username: postgres
      url: jdbc:postgresql://localhost:5432/postgres
      type: com.alibaba.druid.pool.DruidDataSource
#  devtools:
#    restart:
#      enabled: false#mybatis
mybatis:
  # type-aliases-package批量设置别名作用：就是在mapper.xml文件中直接写类名，不配置就需要写类的全路径名
  type-aliases-package: com.example.GrandWorldG.entity
  mapper-locations:  classpath:/mapper/*Mapper.xml
#  mapper、model采用mybatis-generator-core自动解析数据库生成
#  gradle构建时src/main/java目录下的非.java结尾的文件不会被编译，所以需要将myabtis对应的xml文件移至resources目录，并在application.yaml文件配置路径